name: 'Issues to Json'
description: 'Generate JSON from GitHub issues'
author: 'xaoxuu'

inputs:
  data_path:
    description: '数据文件存储路径（主题会读取这个路径，不要随便修改）'
    required: false
    default: '/v2/data.json'
  sort:
    description: 'Issue排序方式和方向 (例如: created-desc/created-asc/updated-desc/updated-asc/version-desc/posts-desc)'
    required: false
    default: 'posts-desc'
  exclude_issue_with_labels:
    description: '需要排除包含哪些标签的Issue (逗号分隔)'
    required: false
    default: '审核中'
  hide_labels:
    description: '需要在前端隐藏的Issue标签，不会写入JSON文件中 (逗号分隔)'
    required: false
    default: '白名单'


runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'message-circle'
  color: 'orange'
